---
- name: Install nginx package
  yum: name=nginx state=present

# - name: Copy nginx configuration
#   template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
#   notify: restart nginx

- name: Enable nginx service
  service: name=nginx state=started enabled=yes
