---
# This role installs HAProxy and configures it.

- name: Download and install haproxy
  yum: name=haproxy state=present

- import_tasks: preparecert.yml

- name: Create haproxy configuration
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: restart haproxy

#haproxy may need additional selinux setup for default config
#setsebool -P haproxy_connect_any 1
#or
#semanage port -a -t PORT_TYPE -p tcp 5002
#where PORT_TYPE is one of the following: http_cache_port_t, http_port_t

- name: Start the haproxy service
  service: name=haproxy state=started enabled=yes
