---
# This role installs php-fpm and configures it.

- name: Install php-fpm and deps
  yum: name={{ item }} state=present
  with_items:
    #- php #Apache httpd module
    - php-fpm
    # - php-enchant
    # - php-IDNA_Convert
    # - php-mbstring
    - php-mysql
    # - php-PHPMailer
    - php-process
    # - php-simplepie
    - php-xml
    - php-gd
    - php-pdo
    - php-pear
    # - php-mcrypt

# - name: Disable default pool
#   command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.disabled creates=/etc/php-fpm.d/www.disabled
#   notify: restart php-fpm

# - name: Copy php-fpm configuration
#   template: src=foo.conf dest=/etc/php-fpm.d/
#   notify: restart php-fpm


#start & enable service
- name: Start the php-fpm service
  service: name=php-fpm state=started enabled=yes
