---
# This role installs php-fpm and configures it.

- name: Install php-fpm and deps
  yum: name={{ item }} state=present
  with_items:
    #- php #Apache httpd module
    - php-fpm
    # - php-enchant
    # - php-IDNA_Convert
    # - php-mbstring
    - php-mysql
    # - php-PHPMailer
    - php-process
    # - php-simplepie
    - php-xml
    - php-gd
    - php-pdo
    - php-pear
    # - php-mcrypt

#start & enable service
- name: Start the php-fpm service
  service: name=php-fpm state=started enabled=yes

- name: Add php-fpm pool configuration
  copy: src=www.conf dest=/etc/php-fpm.d/www.conf mode=644
  notify: restart php-fpm
- name: Add php-fpm global configuration
  copy: src=php-fpm.conf dest=/etc/php-fpm.conf mode=644
  notify: restart php-fpm
#-rw-r--r--. root root system_u:object_r:etc_t:s0       php-fpm.d/www.conf
# setype=foo_t
