---
# Provisioner for Vagrant
# This playbook is intended as one time provisioner. It is not optimized for
# repeted use on same machine, but will work that way as well.
- name: Provisioner playbook
  hosts: all
  # remote_user: vagrant
  become: yes
  roles:
    - common
    - php-fpm
    - nginx
    - haproxy
    - redis
    - mariadb
