---
# This role installs MariaDB and configures it.

- name: Install MariaDB package
  yum: name={{ item }} state=installed
  with_items:
   - mariadb-server
   # - mariadb #installed as dependancy
   # - MySQL-python #prerquisite for mysql ansible modules
  notify: mysql_secure_installation

- name: Start MariaDB Service
  service: name=mariadb state=started enabled=yes
