---
- name: Install MariaDB package
  yum: name={{ item }} state=installed
  with_items:
   - mariadb-server
   - mariadb
   # - MySQL-python

# - name: Configure SELinux to start mysql on any port
#   seboolean: name=mysql_connect_any state=true persistent=yes

# - name: Create Mysql configuration file
#   template: src=my.cnf.j2 dest=/etc/my.cnf
#   notify:
#   - restart mariadb

- name: Start MariaDB Service
  service: name=mariadb state=started enabled=yes
